openapi: 3.1.0
info:
  title: API сервер для проекта «Шесть городов».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0

tags:
  - name: offers
    description: Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'

      responses:
        '201':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '409':
          description: Пользователь с таким email уже существует

        '422':
          description: Ошибка валидации данных

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина (email) и пароля

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'

      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'

        '401':
          description: Неверный логин или пароль

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

      security:
        - bearerAuth: []

      responses:
        '200':
          description: Пользователь авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '401':
          description: Пользователь не авторизован

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.
      responses:
        '200':
          description: Аватар успешно загружен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '400':
          description: Неверный формат файла

        '401':
          description: Не авторизован

  /users/logout:
    post:
      tags:
        - users
      summary: Выход пользователя
      description: Завершает пользовательскую сессию

      responses:
        '204':
          description: Успешный выход

        '401':
          description: Пользователь не авторизован

components:
  schemas:
    CreateUser:
      type: object
      required:
        - email
        - firstname
        - password
        - type
      properties:
        email:
          type: string
          format: email

        firstname:
          type: string
          minLength: 1
          maxLength: 15

        lastname:
          type: string
          minLength: 1
          maxLength: 15

        password:
          type: string
          minLength: 6
          maxLength: 12

        type:
          type: string
          enum: [pro, base]

    LoginUser:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: john@example.com

        password:
          type: string
          example: 123456

    User:
      type: object
      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        email:
          type: string
          example: john@example.com

        firstname:
          type: string
          example: John

        lastname:
          type: string
          example: Doe

        avatarUrl:
          type: string
          example: /uploads/avatar.jpg

        type:
          type: string
          enum: [pro, base]
          example: base

    AuthToken:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
